# Generated by Django 3.2.9 on 2021-12-03 02:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoteSession',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('place', models.TextField(blank=True, default='')),
                # ('is_mandatory', models.BooleanField(default=False)),
                ('open_public', models.BooleanField(default=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='polls.votesession')),
            ],
            options={
                'unique_together': {('session_id', 'datetime')},
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_name', models.CharField(max_length=50)),
                ('preferences', models.CharField(choices=[('UN', 'Unavailable'), ('LE', 'Least Preferred'), ('OK', 'Okay'), ('MOST', 'Most Preferred')], default='UN', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='polls.votesession')),
                ('timeslot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voted_timeslot', to='polls.timeslot')),
            ],
            options={
                'unique_together': {('session_id', 'timeslot_id', 'voter_name')},
            },
        ),
    ]
